dist: xenial
language: python
sudo: yes
python:
- "3.7"
cache: pip
install:
- pip3 install -r requirement.txt
script:
- echo $mongourl
- export Flask_Env=testing
- echo $Flask_Env
- python3 -m pytest -s
